// File generated by FlutterFire CLI.
// ---------------------------------------------------------------------
// ⚠️ REPLACE THIS FILE — do not use these placeholder values.
//
// Run this once from the project root (with your existing Firebase
// project selected):
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// That command overwrites this file with your real project's API keys,
// app IDs, and project ID for each platform (Android/iOS/Web) and wires
// up the native config files automatically. Commit the generated file;
// these are client identifiers, not secrets — access is enforced by
// firestore.rules, not by hiding this file.
// ---------------------------------------------------------------------

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    projectId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    authDomain: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    storageBucket: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGgGpIRZlq9mFl9voEHq9vmnKOyFFOKkg',
    appId: '1:720602671073:android:98d550dfccfae3b0b354a0',
    messagingSenderId: '720602671073',
    projectId: 'wall-dash00',
    storageBucket: 'wall-dash00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    projectId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    storageBucket: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    iosBundleId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
  );
}
